# Generated by Django 4.2.2 on 2023-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
