# Generated by Django 4.1 on 2023-06-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('funds_raised', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
