# Generated by Django 4.1 on 2023-06-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='funds_raised',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
